// ============================================================
// dummyData.js — Realistic UAE Real Estate dummy data
// Used across Dashboard, Courses, Learners, Departments, Reports
// ============================================================

export const DUMMY_DEPARTMENTS = [
  { id: 1, name: 'Property Sales',          hod: 'Ahmed Al Mansoori',   designation: 'VP Sales',              population: 48, learner_count: 42, course_count: 12 },
  { id: 2, name: 'Asset Management',        hod: 'Fatima Al Rashidi',   designation: 'Director Asset Mgmt',   population: 31, learner_count: 28, course_count: 9  },
  { id: 3, name: 'Human Resources',         hod: 'Sara Al Kaabi',       designation: 'HR Director',            population: 22, learner_count: 20, course_count: 11 },
  { id: 4, name: 'Finance & Accounting',    hod: 'Khalid Al Hammadi',   designation: 'CFO',                   population: 27, learner_count: 24, course_count: 8  },
  { id: 5, name: 'Facilities Management',   hod: 'Mariam Al Suwaidi',   designation: 'FM Director',           population: 36, learner_count: 31, course_count: 7  },
  { id: 6, name: 'Legal & Compliance',      hod: 'Omar Al Nuaimi',      designation: 'General Counsel',       population: 18, learner_count: 16, course_count: 10 },
  { id: 7, name: 'Marketing & Branding',    hod: 'Layla Al Shamsi',     designation: 'CMO',                   population: 20, learner_count: 18, course_count: 6  },
  { id: 8, name: 'Customer Experience',     hod: 'Rashed Al Dhaheri',   designation: 'CX Director',           population: 24, learner_count: 22, course_count: 8  },
  { id: 9, name: 'IT & Digital',            hod: 'Noor Al Mazrouei',    designation: 'CTO',                   population: 19, learner_count: 17, course_count: 7  },
  { id:10, name: 'Corporate Strategy',      hod: 'Sultan Al Qasimi',    designation: 'Chief Strategy Officer',population: 14, learner_count: 13, course_count: 5  },
];

export const DUMMY_COURSES = [
  { id: 1, title: 'RERA Certified Broker Programme', description: 'Comprehensive training for real estate brokers in line with RERA regulations and UAE property laws.', institute: 'Dubai Land Department', trainer_name: 'Ahmad Al Farsi', venue: 'DLD Training Centre, Dubai', department_id: 1, start_date: '2025-01-15', end_date: '2025-01-17', duration_hours: 24, duration_days: 3, cost_estimated: 18500, budget_realized: 17800, type: 'External', status: 'Completed', max_learners: 30, po_number: 'PO-2025-001', pr_number: 'PR-2025-001', enrolled_count: 28, stars: 4.7 },
  { id: 2, title: 'Anti-Money Laundering (AML) for Real Estate', description: 'Understanding AML obligations, red flags, and reporting requirements under UAE law.', institute: 'CBUAE Financial Academy', trainer_name: 'Fatema Al Balushi', venue: 'Online – Zoom', department_id: 6, start_date: '2025-02-03', end_date: '2025-02-04', duration_hours: 16, duration_days: 2, cost_estimated: 9200, budget_realized: 9200, type: 'External', status: 'Completed', max_learners: 40, po_number: 'PO-2025-002', pr_number: 'PR-2025-002', enrolled_count: 38, stars: 4.5 },
  { id: 3, title: 'Property Valuation & Appraisal Methods', description: 'Advanced appraisal techniques including income, cost and sales comparison approaches.', institute: 'RICS Middle East', trainer_name: 'Muhammad Al Marri', venue: 'RAK HQ – Conference Room A', department_id: 2, start_date: '2025-02-20', end_date: '2025-02-22', duration_hours: 21, duration_days: 3, cost_estimated: 22000, budget_realized: 21500, type: 'External', status: 'Completed', max_learners: 20, po_number: 'PO-2025-003', pr_number: 'PR-2025-003', enrolled_count: 19, stars: 4.8 },
  { id: 4, title: 'Leadership Excellence for Property Managers', description: 'Developing high-performance leadership behaviours for mid-to-senior management.', institute: 'McKinsey Academy (Internal)', trainer_name: 'Sara Al Kaabi', venue: 'RAK HQ – Boardroom', department_id: 3, start_date: '2025-03-10', end_date: '2025-03-11', duration_hours: 16, duration_days: 2, cost_estimated: 14000, budget_realized: 13200, type: 'Internal', status: 'Completed', max_learners: 25, po_number: 'PO-2025-004', pr_number: 'PR-2025-004', enrolled_count: 23, stars: 4.6 },
  { id: 5, title: 'CRM – Salesforce for Property Sales', description: 'Practical Salesforce training for property sales teams to manage leads and pipeline.', institute: 'Salesforce UAE Partner', trainer_name: 'Noor Al Mazrouei', venue: 'Online – MS Teams', department_id: 1, start_date: '2025-03-25', end_date: '2025-03-26', duration_hours: 14, duration_days: 2, cost_estimated: 11000, budget_realized: 10500, type: 'External', status: 'Completed', max_learners: 35, po_number: 'PO-2025-005', pr_number: 'PR-2025-005', enrolled_count: 34, stars: 4.4 },
  { id: 6, title: 'Strata Title & Owners Association Management', description: 'Legal framework and practical management of jointly owned property under UAE law.', institute: 'RERA – RAK Chapter', trainer_name: 'Omar Al Nuaimi', venue: 'RERA Offices, RAK', department_id: 6, start_date: '2025-04-08', end_date: '2025-04-09', duration_hours: 16, duration_days: 2, cost_estimated: 8500, budget_realized: 8500, type: 'External', status: 'Completed', max_learners: 22, po_number: 'PO-2025-006', pr_number: 'PR-2025-006', enrolled_count: 20, stars: 4.3 },
  { id: 7, title: 'Financial Modelling for Real Estate Projects', description: 'Building Excel-based financial models for development feasibility and IRR analysis.', institute: 'CFI – Corporate Finance Institute', trainer_name: 'Khalid Al Hammadi', venue: 'RAK HQ – Training Room', department_id: 4, start_date: '2025-04-28', end_date: '2025-04-30', duration_hours: 24, duration_days: 3, cost_estimated: 16500, budget_realized: 16000, type: 'External', status: 'Completed', max_learners: 18, po_number: 'PO-2025-007', pr_number: 'PR-2025-007', enrolled_count: 17, stars: 4.9 },
  { id: 8, title: 'Health, Safety & Environment (HSE) – Construction Sites', description: 'UAE-compliant HSE management for facilities professionals on active project sites.', institute: 'NEBOSH Accredited Provider', trainer_name: 'Mariam Al Suwaidi', venue: 'Mina Al Arab Site Office, RAK', department_id: 5, start_date: '2025-05-12', end_date: '2025-05-14', duration_hours: 21, duration_days: 3, cost_estimated: 12800, budget_realized: 12500, type: 'External', status: 'Completed', max_learners: 40, po_number: 'PO-2025-008', pr_number: 'PR-2025-008', enrolled_count: 39, stars: 4.5 },
  { id: 9, title: 'Digital Marketing for Real Estate', description: 'Leveraging social media, SEO and paid advertising to drive property enquiries in UAE.', institute: 'Google Certified Partner', trainer_name: 'Layla Al Shamsi', venue: 'Online – Google Meet', department_id: 7, start_date: '2025-05-26', end_date: '2025-05-27', duration_hours: 14, duration_days: 2, cost_estimated: 7500, budget_realized: 7200, type: 'External', status: 'Completed', max_learners: 20, po_number: 'PO-2025-009', pr_number: 'PR-2025-009', enrolled_count: 18, stars: 4.2 },
  { id: 10, title: 'Negotiation & Closing Techniques – Property Sales', description: 'Advanced negotiation frameworks for high-value UAE property transactions.', institute: 'Huthwaite International', trainer_name: 'Ahmad Al Farsi', venue: 'RAK HQ – Conference Room B', department_id: 1, start_date: '2025-06-16', end_date: '2025-06-17', duration_hours: 14, duration_days: 2, cost_estimated: 13500, budget_realized: 0, type: 'External', status: 'Ongoing', max_learners: 30, po_number: 'PO-2025-010', pr_number: 'PR-2025-010', enrolled_count: 29, stars: 0 },
  { id: 11, title: 'Corporate Governance & Board Reporting', description: 'Best practices in corporate governance, ESG reporting and board presentation.', institute: 'ICD – Institute of Corporate Directors', trainer_name: 'Sultan Al Qasimi', venue: 'RAK HQ – Boardroom', department_id: 10, start_date: '2025-06-23', end_date: '2025-06-24', duration_hours: 16, duration_days: 2, cost_estimated: 19000, budget_realized: 0, type: 'External', status: 'Ongoing', max_learners: 15, po_number: null, pr_number: 'PR-2025-011', enrolled_count: 13, stars: 0 },
  { id: 12, title: 'Property Management – End-to-End Operations', description: 'Full lifecycle property management covering leasing, maintenance and tenant relations.', institute: 'Internal L&D Team', trainer_name: 'Rashed Al Dhaheri', venue: 'RAK HQ – Training Room', department_id: 5, start_date: '2025-07-07', end_date: '2025-07-09', duration_hours: 21, duration_days: 3, cost_estimated: 6000, budget_realized: 0, type: 'Internal', status: 'Pending', max_learners: 35, po_number: null, pr_number: 'PR-2025-012', enrolled_count: 20, stars: 0 },
  { id: 13, title: 'Data Analytics & Power BI for Real Estate', description: 'Using Power BI to visualise property data and generate executive dashboards.', institute: 'Microsoft Learning Partner', trainer_name: 'Noor Al Mazrouei', venue: 'Online – MS Teams', department_id: 9, start_date: '2025-07-21', end_date: '2025-07-22', duration_hours: 14, duration_days: 2, cost_estimated: 10500, budget_realized: 0, type: 'External', status: 'Pending', max_learners: 25, po_number: null, pr_number: 'PR-2025-013', enrolled_count: 0, stars: 0 },
  { id: 14, title: 'Emotional Intelligence for Customer-Facing Roles', description: 'Building EQ skills to improve client satisfaction and handle difficult conversations.', institute: 'Internal L&D Team', trainer_name: 'Sara Al Kaabi', venue: 'RAK HQ – Conference Room A', department_id: 8, start_date: '2025-08-04', end_date: '2025-08-05', duration_hours: 14, duration_days: 2, cost_estimated: 5500, budget_realized: 0, type: 'Internal', status: 'Pending', max_learners: 30, po_number: null, pr_number: 'PR-2025-014', enrolled_count: 0, stars: 0 },
];

export const DUMMY_LEARNERS = [
  { id:1,  emp_id:'RAK-001', name:'Ahmed Al Mansoori',   gender:'Male',   nationality:'Emirati',   department_id:1,  department_name:'Property Sales',       designation:'Senior Sales Executive',          email:'a.mansoori@rakproperties.ae',  status:'Active',              completed_courses:[1,5,10] },
  { id:2,  emp_id:'RAK-002', name:'Layla Khalil',         gender:'Female', nationality:'Jordanian',  department_id:1,  department_name:'Property Sales',       designation:'Sales Executive',                 email:'l.khalil@rakproperties.ae',    status:'Active',              completed_courses:[1,5] },
  { id:3,  emp_id:'RAK-003', name:'Mohammad Al Rashidi',  gender:'Male',   nationality:'Emirati',   department_id:1,  department_name:'Property Sales',       designation:'Sales Manager',                   email:'m.rashidi@rakproperties.ae',   status:'Active',              completed_courses:[1,3,5,10] },
  { id:4,  emp_id:'RAK-004', name:'Priya Nair',           gender:'Female', nationality:'Indian',     department_id:1,  department_name:'Property Sales',       designation:'Sales Coordinator',               email:'p.nair@rakproperties.ae',      status:'Active',              completed_courses:[5] },
  { id:5,  emp_id:'RAK-005', name:'Tariq Al Dhaheri',     gender:'Male',   nationality:'Emirati',   department_id:1,  department_name:'Property Sales',       designation:'Director of Sales',               email:'t.dhaheri@rakproperties.ae',   status:'Active',              completed_courses:[1,5,10,4] },
  { id:6,  emp_id:'RAK-006', name:'Fatima Al Rashidi',    gender:'Female', nationality:'Emirati',   department_id:2,  department_name:'Asset Management',     designation:'Director Asset Mgmt',             email:'f.rashidi@rakproperties.ae',   status:'Active',              completed_courses:[3,7] },
  { id:7,  emp_id:'RAK-007', name:'James Okonkwo',        gender:'Male',   nationality:'Nigerian',   department_id:2,  department_name:'Asset Management',     designation:'Portfolio Manager',               email:'j.okonkwo@rakproperties.ae',   status:'Active',              completed_courses:[3,7] },
  { id:8,  emp_id:'RAK-008', name:'Aisha Al Marzouqi',   gender:'Female', nationality:'Emirati',   department_id:2,  department_name:'Asset Management',     designation:'Asset Analyst',                   email:'a.marzouqi@rakproperties.ae',  status:'Active',              completed_courses:[3] },
  { id:9,  emp_id:'RAK-009', name:'Sara Al Kaabi',        gender:'Female', nationality:'Emirati',   department_id:3,  department_name:'Human Resources',      designation:'HR Director',                     email:'s.kaabi@rakproperties.ae',     status:'Active',              completed_courses:[4,2] },
  { id:10, emp_id:'RAK-010', name:'David Chen',           gender:'Male',   nationality:'Chinese',    department_id:3,  department_name:'Human Resources',      designation:'Talent Acquisition Lead',         email:'d.chen@rakproperties.ae',      status:'Active',              completed_courses:[4] },
  { id:11, emp_id:'RAK-011', name:'Noura Al Hammadi',    gender:'Female', nationality:'Emirati',   department_id:3,  department_name:'Human Resources',      designation:'L&D Specialist',                  email:'n.hammadi@rakproperties.ae',   status:'Active',              completed_courses:[4] },
  { id:12, emp_id:'RAK-012', name:'Khalid Al Hammadi',   gender:'Male',   nationality:'Emirati',   department_id:4,  department_name:'Finance & Accounting', designation:'CFO',                             email:'k.hammadi@rakproperties.ae',   status:'Active',              completed_courses:[7,2] },
  { id:13, emp_id:'RAK-013', name:'Meena Pillai',         gender:'Female', nationality:'Indian',     department_id:4,  department_name:'Finance & Accounting', designation:'Finance Manager',                 email:'m.pillai@rakproperties.ae',    status:'Active',              completed_courses:[7] },
  { id:14, emp_id:'RAK-014', name:'Saleh Al Nuaimi',     gender:'Male',   nationality:'Emirati',   department_id:4,  department_name:'Finance & Accounting', designation:'Senior Accountant',               email:'s.nuaimi@rakproperties.ae',    status:'Active',              completed_courses:[7,2] },
  { id:15, emp_id:'RAK-015', name:'Mariam Al Suwaidi',   gender:'Female', nationality:'Emirati',   department_id:5,  department_name:'Facilities Management',designation:'FM Director',                     email:'m.suwaidi@rakproperties.ae',   status:'Active',              completed_courses:[8] },
  { id:16, emp_id:'RAK-016', name:'Raj Kumar',            gender:'Male',   nationality:'Indian',     department_id:5,  department_name:'Facilities Management',designation:'Maintenance Supervisor',          email:'r.kumar@rakproperties.ae',     status:'Active',              completed_courses:[8] },
  { id:17, emp_id:'RAK-017', name:'Hessa Al Falasi',     gender:'Female', nationality:'Emirati',   department_id:5,  department_name:'Facilities Management',designation:'Facilities Coordinator',          email:'h.falasi@rakproperties.ae',    status:'Active',              completed_courses:[8] },
  { id:18, emp_id:'RAK-018', name:'Omar Al Nuaimi',      gender:'Male',   nationality:'Emirati',   department_id:6,  department_name:'Legal & Compliance',   designation:'General Counsel',                 email:'o.nuaimi@rakproperties.ae',    status:'Active',              completed_courses:[6,2] },
  { id:19, emp_id:'RAK-019', name:'Sophie Martin',        gender:'Female', nationality:'French',     department_id:6,  department_name:'Legal & Compliance',   designation:'Legal Counsel',                   email:'s.martin@rakproperties.ae',    status:'Active',              completed_courses:[6,2] },
  { id:20, emp_id:'RAK-020', name:'Ali Al Muhairi',      gender:'Male',   nationality:'Emirati',   department_id:6,  department_name:'Legal & Compliance',   designation:'Compliance Officer',              email:'a.muhairi@rakproperties.ae',   status:'Active',              completed_courses:[2,6] },
  { id:21, emp_id:'RAK-021', name:'Layla Al Shamsi',     gender:'Female', nationality:'Emirati',   department_id:7,  department_name:'Marketing & Branding', designation:'CMO',                             email:'l.shamsi@rakproperties.ae',    status:'Active',              completed_courses:[9] },
  { id:22, emp_id:'RAK-022', name:'Carlos Rivera',        gender:'Male',   nationality:'Spanish',    department_id:7,  department_name:'Marketing & Branding', designation:'Brand Manager',                   email:'c.rivera@rakproperties.ae',    status:'Active',              completed_courses:[9] },
  { id:23, emp_id:'RAK-023', name:'Rashed Al Dhaheri',   gender:'Male',   nationality:'Emirati',   department_id:8,  department_name:'Customer Experience',  designation:'CX Director',                     email:'r.dhaheri@rakproperties.ae',   status:'Active',              completed_courses:[] },
  { id:24, emp_id:'RAK-024', name:'Amna Al Mazrouei',    gender:'Female', nationality:'Emirati',   department_id:8,  department_name:'Customer Experience',  designation:'Customer Relations Manager',      email:'a.mazrouei@rakproperties.ae',  status:'Active',              completed_courses:[] },
  { id:25, emp_id:'RAK-025', name:'Noor Al Mazrouei',    gender:'Female', nationality:'Emirati',   department_id:9,  department_name:'IT & Digital',         designation:'CTO',                             email:'n.mazrouei@rakproperties.ae',  status:'Active',              completed_courses:[5] },
  { id:26, emp_id:'RAK-026', name:'Vikram Singh',         gender:'Male',   nationality:'Indian',     department_id:9,  department_name:'IT & Digital',         designation:'Senior Developer',                email:'v.singh@rakproperties.ae',     status:'Active',              completed_courses:[5] },
  { id:27, emp_id:'RAK-027', name:'Sultan Al Qasimi',    gender:'Male',   nationality:'Emirati',   department_id:10, department_name:'Corporate Strategy',   designation:'Chief Strategy Officer',          email:'s.qasimi@rakproperties.ae',    status:'Active',              completed_courses:[4,11] },
  { id:28, emp_id:'RAK-028', name:'Emma Walsh',           gender:'Female', nationality:'Irish',      department_id:10, department_name:'Corporate Strategy',   designation:'Strategy Manager',                email:'e.walsh@rakproperties.ae',     status:'Active',              completed_courses:[4] },
  { id:29, emp_id:'RAK-029', name:'Hassan Al Blooshi',   gender:'Male',   nationality:'Emirati',   department_id:1,  department_name:'Property Sales',       designation:'Sales Executive',                 email:'h.blooshi@rakproperties.ae',   status:'Resigned/Terminated', completed_courses:[1] },
  { id:30, emp_id:'RAK-030', name:'Dina Al Harthi',      gender:'Female', nationality:'Emirati',   department_id:3,  department_name:'Human Resources',      designation:'HR Coordinator',                  email:'d.harthi@rakproperties.ae',    status:'Resigned/Terminated', completed_courses:[] },
];

export const DUMMY_TRAINERS = [
  { id:1,  name:'Ahmad Al Farsi',    institute:'Dubai Land Department',       expertise:['RERA Regulations','Real Estate Law','Contract Law'],      rating:4.8, phone:'+971 50 234 5678', email:'a.farsi@dld.gov.ae',           type:'External', bio:'Certified RERA instructor with 12 years training real estate professionals across the UAE. Former senior regulatory officer at DLD.' },
  { id:2,  name:'Fatema Al Balushi', institute:'CBUAE Financial Academy',     expertise:['AML Compliance','Financial Crime','Risk Management'],      rating:4.6, phone:'+971 55 876 5432', email:'f.balushi@cbuae.ae',           type:'External', bio:'AML specialist and certified compliance trainer with over 200 sessions delivered to banks and real estate firms across the GCC.' },
  { id:3,  name:'Muhammad Al Marri', institute:'RICS Middle East',            expertise:['Property Valuation','RICS Standards','Investment Analysis'],rating:4.9, phone:'+971 56 543 2198', email:'m.marri@rics.org',             type:'External', bio:'MRICS qualified valuer with 15 years in commercial and residential appraisal across UAE, KSA and Qatar.' },
  { id:4,  name:'Sara Al Kaabi',     institute:'RAK Properties',              expertise:['Leadership','Change Management','HR Strategy'],             rating:4.7, phone:'+971 50 111 2233', email:'s.kaabi@rakproperties.ae',     type:'Internal', bio:'HR Director and certified executive coach. Has led transformation programmes impacting over 500 employees at RAK Properties.' },
  { id:5,  name:'Noor Al Mazrouei',  institute:'Microsoft Learning Partner',  expertise:['Power BI','Salesforce CRM','Digital Transformation'],       rating:4.5, phone:'+971 52 987 6541', email:'n.mazrouei@rakproperties.ae', type:'Internal', bio:'CTO of RAK Properties and certified Microsoft and Salesforce trainer. Spearheaded the company\'s digital transformation roadmap.' },
  { id:6,  name:'Omar Al Nuaimi',    institute:'RERA – RAK Chapter',          expertise:['Strata Law','Corporate Law','Regulatory Compliance'],       rating:4.4, phone:'+971 56 321 9870', email:'o.nuaimi@rakproperties.ae',   type:'Internal', bio:'General Counsel at RAK Properties with deep expertise in UAE property law, strata title and RERA regulatory frameworks.' },
  { id:7,  name:'Khalid Al Hammadi', institute:'CFI – Corporate Finance',     expertise:['Financial Modelling','Excel','Real Estate Finance'],        rating:4.8, phone:'+971 50 654 3210', email:'k.hammadi@rakproperties.ae',  type:'Internal', bio:'CFO and chartered accountant with CFA designation. Pioneered financial modelling standards for real estate projects at RAK Properties.' },
  { id:8,  name:'Mariam Al Suwaidi', institute:'NEBOSH Accredited Provider',  expertise:['HSE Management','Construction Safety','Risk Assessment'],   rating:4.6, phone:'+971 55 432 1098', email:'m.suwaidi@rakproperties.ae',  type:'Internal', bio:'NEBOSH certified HSE Director with 10 years of site safety management on major UAE construction projects.' },
  { id:9,  name:'Layla Al Shamsi',   institute:'Google Certified Partner',    expertise:['Digital Marketing','SEO','Social Media Strategy'],          rating:4.3, phone:'+971 52 765 4321', email:'l.shamsi@rakproperties.ae',   type:'Internal', bio:'CMO and Google certified digital marketer. Led award-winning campaigns for Mina Al Arab and Al Hamra Village launches.' },
  { id:10, name:'Rashed Al Dhaheri', institute:'RAK Properties',              expertise:['Customer Experience','Property Management','CRM'],          rating:4.5, phone:'+971 50 876 5432', email:'r.dhaheri@rakproperties.ae',  type:'Internal', bio:'CX Director with expertise in customer journey mapping and service excellence for luxury real estate clients.' },
];

export const SATISFACTION_TREND = [
  { month: 'Jan', score: 4.1 }, { month: 'Feb', score: 4.2 },
  { month: 'Mar', score: 4.3 }, { month: 'Apr', score: 4.3 },
  { month: 'May', score: 4.4 }, { month: 'Jun', score: 4.5 },
];
export const SATISFACTION_TREND_QUARTERLY = [
  { month: 'Q1', score: 4.2 }, { month: 'Q2', score: 4.4 },
];

export const COURSES_BY_MONTH = [
  { month: 'Jan', courses: 2 }, { month: 'Feb', courses: 3 },
  { month: 'Mar', courses: 2 }, { month: 'Apr', courses: 3 },
  { month: 'May', courses: 2 }, { month: 'Jun', courses: 2 },
];
export const COURSES_BY_QUARTER = [
  { month: 'Q1', courses: 7 }, { month: 'Q2', courses: 7 },
];

export const UPCOMING_TRAINING = [
  { date: '16 June', title: 'Negotiation & Closing',  trainer: 'Ahmad A.',  dept: 'Property Sales',    enrolled: 29 },
  { date: '23 June', title: 'Corporate Governance',   trainer: 'Sultan Q.', dept: 'Corporate Strategy',enrolled: 13 },
  { date: '7 July',  title: 'Property Management',    trainer: 'Rashed D.', dept: 'Facilities Mgmt',   enrolled: 20 },
  { date: '21 July', title: 'Power BI Analytics',     trainer: 'Noor M.',   dept: 'IT & Digital',      enrolled: 0  },
];

export const REPORTS_SATISFACTION = [
  { month: 'Jan', score: 78 }, { month: 'Feb', score: 80 },
  { month: 'Mar', score: 79 }, { month: 'Apr', score: 83 },
  { month: 'May', score: 85 }, { month: 'Jun', score: 87 },
  { month: 'Jul', score: 82 }, { month: 'Aug', score: 88 },
  { month: 'Sep', score: 90 }, { month: 'Oct', score: 86 },
  { month: 'Nov', score: 91 }, { month: 'Dec', score: 93 },
];